### PR TITLE
XMLHttpRequest

### PR DESCRIPTION
**Pull request by KikoPT1234**
I created this pull request so that we can discuss the `XMLHttpRequest` implementation I'm doing.
It's not perfect, I want someone with more experience to help and make it better.
I put `XMLHttpRequest` in the `http` module since I didn't know where else to put it, so check that as well.
*This pull request is **not** ready to be merged*

### CODE REVIEW

**Comment by Cormanz** [comment]
Looks pretty good so far, nice work!

**Comment by Cormanz** [comment]
How's progress on this going? There hasn't been a commit in a while.

**Comment by KikoPT1234** [comment]
I'm full of school work and other projects, feel free to contribute yourself if you want.

**Comment by KikoPT1234** [comment]
Yeah I don't think I'm gonna work more on this, feel free to reopen with additions, though.
Good luck with Velt.

**Pull request closed without merging**
